---
title: "Tables and Figures"
format: docx
prefer-html: true
execute: 
  echo: false
---

```{r}
#| label: setup
#| include: false
library(here)
source(here("check_packages.R"))
load(here("data","data_constructed","analytical_data.RData"))
options(knitr.kable.NA = "")
```

```{r}
#| label: tbl-partition

model_base_disc <- lmer(h_index ~ 1+(1 | discipline), data=scholars_imp[[1]])

models_base_big_field <- scholars_imp[[1]] %>%
  group_by(big_field) %>%
  group_split() %>%
  map(~ lmer(h_index ~ 1+(1 | discipline), data=.x))

models_partition <- c(model_base_disc, models_base_big_field)

tbl_partition <- map(models_partition, function(x) {
              temp <- icc_specs(x) |>
                select(grp, percent)  |>
  mutate(grp=ifelse(grp=="discipline:field", "field", grp),
         grp=factor(grp, levels=c("discipline","field","Residual"),
                    labels=c("Between discipline","Field","Within Discipline")))
            }) |>
  reduce(full_join, by="grp") |>
  arrange(grp)

colnames(tbl_partition) <- c("Grouping","All", 
                             levels(scholars_imp[[1]]$big_field))

tbl_partition |> 
  gt() |>
  fmt_percent(columns = c(All, Humanities, Medical, Professional, 
                          "Social Sciences", STEM),
              decimals=1, scale=FALSE) |>
  tab_spanner("By Field", columns = levels(scholars_imp[[1]]$big_field)) |>
  tab_header(title="Parition of variance in h-index scores between and within disciplines")
```


Regression tables will not show up in the word document but will instead be placed in separate MS word documents.

```{r}
#| label: models-all
#| include: false

formula_pfemale <- formula(
  h_index ~ I(prop_female-disc_prop_female)+I(100*disc_prop_female)+
    (1|discipline))

formula_psole <- formula(
  h_index ~ I(100*(prop_sole-disc_prop_sole))+log(100*disc_prop_sole)+
    (1|discipline))

# main effects are group mean centered
formula_disc <- formula(
  h_index ~ 
    I(prop_female-disc_prop_female)+I(100*disc_prop_female)+
    +I(100*(prop_sole-disc_prop_sole))+log(100*disc_prop_sole)+
    (1|discipline))

# add a model with controls for age, specialization and the number of elite 
# scholars per university (all grand mean centered)
formula_controls <- update(formula_disc, .~.+I(age-mean(age))+
                             I(specialization-mean(specialization))+
                             scale(uni_pub_cnt))

# creat coef labels for most complex model
coef_labels <- c("Intercept",
                 "Prob. [0-1] of female name (disc. mean ctr.)",
                 "Disc. mean percent female name",
                 "Percent sole authored pubs (disc. mean ctr.)",
                 "Disc. mean percent sole authored pubs (logged)",
                 "Career length (grand mean centered)",
                 "Specialization [0-1] (grand mean ctr.)",
                 "Highly productive university count (stdized)")

models_wb_pfemale <- map(scholars_imp, ~lmer(formula_pfemale, data=.x))
models_wb_psole <- map(scholars_imp, ~lmer(formula_psole, data=.x))
models_wb_disc <- map(scholars_imp, ~lmer(formula_disc, data=.x))
models_wb_controls <- map(scholars_imp, ~lmer(formula_controls, data=.x))

wordreg(lapply(list(models_wb_pfemale, models_wb_psole, models_wb_disc,
                    models_wb_controls), pool),
        custom.coef.names = coef_labels,
        digits=2,
        #custom.model.names = c("Prop female", "Prop sole","Combined","W/controls"),
        caption = "Multilevel models predicting H-index score across all disciplines. Clustering at the disciplinary level.",
        caption.above = TRUE,
        file="models_all.doc")
```

```{r}
#| label: models-big-field
#| include: false
  
big_fields <- levels(scholars_imp[[1]]$big_field)
models_full_big_field <- map(big_fields, function(x) {
  models <- map(scholars_imp, function(df) {
    df <- df |>
      filter(big_field==x)
    return(lmer(formula_controls, data=df))
  })
  return(pool(models))
})

wordreg(models_full_big_field, 
        caption="Multilevel models predicting H-index score within each field. Clustering at the disciplinary level.",
        custom.coef.names = coef_labels,
        custom.model.names = big_fields,
        caption.above = TRUE,
        file="models_field.doc")  
```  